# Generated by Django 3.0.5 on 2020-04-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faq',
            new_name='Faqs',
        ),
    ]
