# Generated by Django 3.0.5 on 2020-04-19 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200419_2257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faqs',
            new_name='faq',
        ),
    ]
